name: playerqr
main: com.sovereigncraft.playerqr.Main
author: Sovtoshi
version: 1.0
api-version: 1.13
commands:
  playerqr:
    description: Create a Private QR
    usage: /playerqr <text|link>
    permission: qrcodemap.create
    aliases:
      - privateqr
      - pqr
  screen:
    description: a dynamic updating map for private commands
    usage: /screen
    permission: qrcodemap.create
  qrcode:
    description: Create a QR-Code
    usage: /qrcode <text|link>
    permission: qrcodemap.create
    aliases:
      - qr
      - qc